import type { SiteConfig } from "@/types/site-config";

export const defaultConfig: SiteConfig = {
  general: {
    businessName: "A&B Barber Lounge 2",
    phone: "+45 91 75 24 70",
    address: "Perlegade 64, Sønderborg",
    hours: "Man–Lør: 09–18 · Søn: lukket",
    planwayUrl: "https://ab-barberlounge2.planway.com",
    instagram: "https://www.instagram.com/abbarberlounge/reels/",
    facebook: "https://www.facebook.com/Perlegade64/",
    tiktok: "https://www.tiktok.com/@abbarberlounge",
  },
  images: {
    hero: "",
    about: "",
    services: "",
  },
  hero: {
    badge: "Nyåbnet · Sønderborg",
    headline1: "A&B Barber Lounge 2",
    headline2: "Klip uden grænser.",
    subtext: "Ubegrænset klip fra 499 kr/md — eller klip & skæg for 599 kr/md. Drop-in eller book online.",
    ctaBook: "Book din tid",
    stats: [
      { value: "499", label: "kr/md klip" },
      { value: "599", label: "kr/md klip & skæg" },
      { value: "10+", label: "års erfaring" },
    ],
  },
  about: {
    badge: "Om os",
    welcomePrefix: "Velkommen til",
    nameDisplay: "A&B Barberlounge2",
    introPrefix: "Mit navn er",
    ownerName: "Wasim",
    intro: "og jeg er indehaver af A&B Barberlounge2 i Sønderborg.",
    bio1: "Jeg er uddannet frisør fra Damaskus og har over 10 års erfaring i branchen. Jeg har desuden et certificeret herrefrisørkursus fra Københavns Professionshøjskole, hvilket sikrer moderne teknikker og høj faglig kvalitet.",
    bio2: "Hos os får du en skarp klipning og professionel skægtrimning i rolige omgivelser med fokus på kvalitet og detaljer.",
    cert1Title: "Certificeret",
    cert1Sub: "Københavns Professionshøjskole",
    cert2Title: "Uddannet",
    cert2Sub: "Frisør fra Damaskus",
    yearsExp: "10+",
    yearsLabel: "års erfaring",
  },
  offer: {
    badge: "Vores medlemskaber",
    heading1: "To medlemskaber.",
    heading2: "Ubegrænset velpleje.",
    subtext: "Vælg det medlemskab der passer dig — kun klip, eller klip kombineret med skæg.",
    smallPrint: "Ingen oprettelsesgebyr · Opsig når som helst",
  },
  servicesSection: {
    badge: "Vores håndværk",
    heading: "Hver klip er en kunstform.",
    body: "Hos A&B Barber Lounge 2 i Sønderborg kombinerer vi klassisk barberhåndværk med moderne teknikker. Vores barbere uddannes løbende — så du altid får det skarpeste resultat.",
    cta: "Se alle services",
  },
  gallery: {
    badge: "Galleri",
    heading: "Et kig indenfor.",
    images: [
      { id: "1", url: "gallery/chairs.jpg",     alt: "Sorte og guld barberstole" },
      { id: "2", url: "gallery/shave.jpg",       alt: "Barbering med varm håndklædebehandling" },
      { id: "3", url: "gallery/storefront.jpg",  alt: "Facaden af A&B Barber Lounge 2" },
      { id: "4", url: "gallery/salon.jpg",       alt: "Salon interiør" },
    ],
  },
  contact: {
    badge: "Besøg os",
    heading: "Drop-in eller book online.",
    body: "Du finder os midt i Sønderborg. Kig forbi for et klip, eller reservér din tid med få klik.",
    cardHeading: "Klar til et nyt klip?",
    cardBody: "Book din tid online via vores bookingsystem — det tager under 30 sekunder.",
    cardCta: "Gå til booking",
  },
  pages: {
    services: {
      badge: "Services",
      heading1: "Priser &",
      heading2: "behandlinger",
      subtext: "Transparente priser. Ingen overraskelser. Bliv medlem og få det hele ubegrænset.",
    },
    booking: {
      badge: "Book tid",
      heading1: "Reservér din",
      heading2: "stol",
      subtext: "Vælg tid og service nedenfor — eller ring til os for drop-in.",
      iframeHeading: "Online booking",
      iframeSubtext: "Drevet af Planway",
      iframeCta: "Åbn i nyt vindue",
    },
  },
  faqSection: {
    badge: "FAQ",
    heading: "Ofte stillede spørgsmål",
  },
  socialSection: {
    badge: "Følg os",
    heading: "Se os på Instagram",
    instagramHandle: "@abbarberlounge",
    followers: "286",
    posts: "91",
    items: [
      { id: "1", url: "gallery/chairs.jpg",     alt: "Sorte og guld barberstole",              date: "Maj 2025" },
      { id: "2", url: "gallery/shave.jpg",       alt: "Barbering med varm håndklædebehandling", date: "Apr 2025" },
      { id: "3", url: "gallery/storefront.jpg",  alt: "Facaden af A&B Barber Lounge 2",         date: "Mar 2025" },
      { id: "4", url: "gallery/salon.jpg",       alt: "Salon interiør",                         date: "Feb 2025" },
    ],
  },
  services: [
    { id: "1", icon: "scissors", title: "Herreklip",      price: "200 kr",    time: "30 min", desc: "Klassisk eller moderne klipning, vask og styling inkluderet." },
    { id: "2", icon: "beard",    title: "Skægtrim",       price: "149 kr",    time: "20 min", desc: "Præcis trimning og formgivning af dit skæg." },
    { id: "3", icon: "flame",    title: "Varm Barbering", price: "199 kr",    time: "25 min", desc: "Klassisk barbering med varmt håndklæde og barberkniv." },
    { id: "4", icon: "scissors-beard", title: "Klip + Skæg",   price: "349 kr",    time: "45 min", desc: "Den komplette pakke — klipning og fuld skægbehandling." },
    { id: "5", icon: "crown",    title: "Den Royale",     price: "499 kr",    time: "60 min", desc: "Klip, skæg, ansigtsmaske og massage. Vores signaturoplevelse." },
    { id: "6", icon: "baby",     title: "Børneklip (0–12)", price: "179 kr", time: "20 min", desc: "Tålmodig klipning for de små i en rolig stol." },
    { id: "7", icon: "droplet",  title: "Hårfarve",       price: "fra 299 kr", time: "30 min", desc: "Dækning af grå hår eller fuld farveændring." },
    { id: "8", icon: "gift",     title: "Gavekort",       price: "valgfrit",  time: "—",     desc: "Den perfekte gave til ham. Fås i alle beløb." },
  ],
  memberships: [
    {
      id: "1",
      name: "Klip Medlemskab",
      price: "499",
      tagline: "Ubegrænset herreklip hver måned.",
      perks: [
        "Ubegrænset antal klipninger",
        "Drop-in eller online booking",
        "Også samme dag",
        "Ingen binding — opsig når du vil",
      ],
      cta: "Vælg Klip 499",
      highlight: false,
    },
    {
      id: "2",
      name: "Klip & Skæg Medlemskab",
      price: "599",
      tagline: "Klip + skæg og skægtrimning ubegrænset.",
      perks: [
        "Ubegrænset herreklip",
        "Ubegrænset skæg & skægtrim",
        "Drop-in eller online booking",
        "10% rabat på produkter",
        "Ingen binding — opsig når du vil",
      ],
      cta: "Vælg Klip & Skæg 599",
      highlight: true,
    },
  ],
  faq: [
    {
      id: "1",
      question: "Hvad koster et herreklip i Sønderborg?",
      answer: "Prisen på et herreklip afhænger af behandling, erfaring og salonens koncept. Hos A&B Barber Lounge 2 i Sønderborg tilbyder vi både almindelige klipninger og unlimited abonnementer fra 499 kr/md til kunder, der ønsker faste klipninger hver måned.",
    },
    {
      id: "2",
      question: "Kan man få drop-in hos en barber i Sønderborg?",
      answer: "Ja, mange barberer tilbyder drop-in, men der kan være ventetid i travle perioder. Hos A&B Barber Lounge 2 har du mulighed for både drop-in og online booking, så du nemt kan vælge den løsning, der passer bedst til din hverdag.",
    },
    {
      id: "3",
      question: "Hvor ofte bør man blive klippet?",
      answer: "De fleste vælger at blive klippet hver 2–3 uge for at holde frisuren skarp. Kortere fades og præcise overgange kræver ofte hyppigere vedligeholdelse, mens længere frisurer typisk kan holde formen i længere tid.",
    },
    {
      id: "4",
      question: "Hvad er forskellen på barber og frisør?",
      answer: "En barber arbejder primært med herreklip, fades og skægtrimning, mens en frisør ofte dækker bredere behandlinger til både mænd og kvinder. Hos A&B Barber Lounge 2 kombinerer vi klassisk barberhåndværk med moderne herreklip og styling.",
    },
    {
      id: "5",
      question: "Er unlimited klip abonnement det værd?",
      answer: "Unlimited klip abonnement kan være en fordel for dig, der ønsker at holde frisuren skarp hele måneden uden at betale for hver enkelt klipning. Mange vælger abonnementsløsningen for nemheds skyld og for at kunne blive klippet oftere.",
    },
    {
      id: "6",
      question: "Hvor lang tid tager en herreklipning?",
      answer: "En herreklipning tager som regel mellem 20 og 40 minutter afhængigt af frisure, længde og behandling. Hvis der også skal trimmes eller styles skæg, kan behandlingen tage lidt længere tid.",
    },
  ],
  reviews: [
    { id: "1", author: "Manzar Malik",            initials: "MM", avatarUrl: "https://lh3.googleusercontent.com/a/ACg8ocLD8AoHZZD08HSr4Usc5w-LryQfIcYg7iuGjxh9FOXBAOTt3Q=w96-h96-p-rp-mo-ba4-br100", rating: 5, text: "Had a really pleasant experience he did exactly same haircut what i asked and beard trimming was also nice.", date: "For 18 timer siden" },
    { id: "2", author: "Catalin Cercel",           initials: "CC", avatarUrl: "https://lh3.googleusercontent.com/a/ACg8ocJ3rSxGAsCbDQfKIh2HlPWNQMMgY554k0Sy6OvDGaJlIb09mA=w96-h96-p-rp-mo-br100",          rating: 5, text: "Professional haircut. 👌",                                                                                     date: "For 5 dage siden"  },
    { id: "3", author: "Aladdin Oudeh",            initials: "AO", avatarUrl: "https://lh3.googleusercontent.com/a/ACg8ocLoNmDmsQYe3g2dRqNrz6c75mWx8UdnO4JBGe9cnaqO2LgHww=w96-h96-p-rp-mo-br100",          rating: 5, text: "We're good service and it's professional work Wasim done",                                                    date: "For 1 uge siden"   },
    { id: "4", author: "Sønderborg Pizza & Grill", initials: "SP", avatarUrl: "https://lh3.googleusercontent.com/a/ACg8ocKo01t4FxUQbuxTGPB1ozjy12z4HtkQ8gTfFWAidjoTlpnvuQ=w96-h96-p-rp-mo-br100",          rating: 5, text: "A beautiful haircut, I recommend it.",                                                                       date: "For 1 måned siden" },
    { id: "5", author: "Rizan Hannan",             initials: "RH", avatarUrl: "https://lh3.googleusercontent.com/a/ACg8ocJFLqRBNhxbUdkjtcKVJBAXyPgHENeuvXllSBiNAfb8mP9UFQ=w96-h96-p-rp-mo-br100",          rating: 5, text: "Good service, nice mood and skilled hairdresser",                                                              date: "For 1 dag siden"   },
    { id: "6", author: "Sedin",                    initials: "SE", avatarUrl: "https://lh3.googleusercontent.com/a-/ALV-UjWMmsVVqJcu9YQtKyQi1qu6TmQl_Bu9NsCabkFpC2lwg1xo5GQ=w96-h96-p-rp-mo-br100",         rating: 5, text: "Good haircut, good service and great mood. Definitely recommended 😊",                                        date: "For 2 dage siden"  },
  ],
  seo: {
    canonicalBase: "https://ab-barberlounge2.dk",
    ogImage: "https://ab-barberlounge2.dk/og-image.jpg",
    home: {
      title: "A&B Barber Lounge 2 Sønderborg — Ubegrænset klip 499 kr/md",
      description: "A&B Barber Lounge 2 i Sønderborg. Ubegrænset herreklip fra 499 kr/md eller klip & skæg for 599 kr/md. Drop-in eller online booking. Perlegade 64. Ring 91 75 24 70.",
    },
    services: {
      title: "Services & Priser — A&B Barber Lounge 2 Sønderborg",
      description: "Se alle vores barbertjenester og priser. Herreklip fra 200 kr, skægtrimning, varm barbering og mere. Bliv medlem og få ubegrænset klip fra 499 kr/md.",
    },
    booking: {
      title: "Book tid — A&B Barber Lounge 2 Sønderborg",
      description: "Book din tid online hos A&B Barber Lounge 2 i Sønderborg. Hurtig og nem booking via Planway. Drop-in velkommen man–lør 09–18.",
    },
  },
};
